service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'
  environment:
    USER_TABLE: users
    PRODUCT_TABLE: products
    JWT_SECRET: asdklajhgailsdhlagiaijdfasfjkaf
    JWT_EXPIRES_IN: 3600

package:
  individually: true
  patterns:
    - .git/**
    - .dynamodb/**

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: users
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: products
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            # ProvisionedThroughput:
            #   ReadCapacityUnits: 5
            #   WriteCapacityUnits: 5

    # ImageS3Bucket:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: demo-bucket
plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
